### ISSUE TITLE
Upgrade to 2.12.0

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Broadsea-WebTools#14]
Hi @leeevans -- I'd like to use Atlas/WebAPI 2.12.0 in Broadsea. From what I can tell, until the WAR file is published to nexus, we can't have the Dockerfile pull this version. 

Can we get the 2.12.0 WAR file out in the Nexus repo?

**Comment by chgl** [comment]
maybe we could update this repository to use the pre-built images for ATLAS and the WebAPI. In a docker-compose file it would look something like this (with traefik for convenience, missing mounting of config files):

```yaml
services:
  traefik:
    image: docker.io/library/traefik:v2.9.4@sha256:4c388f477f5b7aa48420694d90db0ecb96b4ecede60b9b7589c87858abf87b60
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    read_only: true
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ohdsi-db:
    image: docker.io/library/postgres:15.0@sha256:bab8d7be6466e029f7fa1e69ff6aa0082704db330572638fd01f2791824774d8
    restart: unless-stopped
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    shm_size: 1024m
    privileged: false
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ohdsi

  ohdsi-webapi:
    image: docker.io/ohdsi/webapi:2.12.0@sha256:4d951a05245cedad4d666874fb71f182bd2140aab5ece4f1621d028cf10d0823
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    privileged: false
    environment:
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://ohdsi-db:5432/ohdsi
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://ohdsi-db:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_PASSWORD: postgres
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi
      SECURITY_CORS_ENABLED: "true"
      SECURITY_ORIGIN: "http://broadsea-webtools.127.0.0.1.nip.io"
    depends_on:
      - ohdsi-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ohdsi-webapi.rule=Host(`broadsea-webtools.127.0.0.1.nip.io`) && PathPrefix(`/WebAPI`)"
      - "traefik.http.routers.ohdsi-webapi.entrypoints=web"

  ohdsi-atlas:
    image: docker.io/ohdsi/atlas:2.12.0@sha256:96431e12cba41643117a904f14c3c6d50a0af63a9a293ed61cd56d5bcffb723a
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    environment:
      WEBAPI_URL: "http://broadsea-webtools.127.0.0.1.nip.io/WebAPI/"
    depends_on:
      - ohdsi-webapi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ohdsi-atlas.rule=Host(`broadsea-webtools.127.0.0.1.nip.io`) && PathPrefix(`/atlas`)"
      - "traefik.http.routers.ohdsi-atlas.entrypoints=web"
```

ATLAS is then accessible at <http://broadsea-webtools.127.0.0.1.nip.io/atlas/#/home>.

Although I don't know if this belongs here or in the https://github.com/OHDSI/Broadsea repository, I'd be happy to create a PR?
